<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQte($qte){
        return $this->createQueryBuilder('p')
            ->where('p.quantity > :quantity')
            ->setParameters(['quantity'=>$qte])
            ->getQuery()
            ->getResult();
    }
}
